name: Terraform Workflow

on:
  push:
    paths:
      - 'main.tf'

jobs:
  run-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Set environment variables
      run: |
        echo "TF_VAR_pr_access_token=${{ secrets.TF_VAR_pr_access_token }}" >> $GITHUB_ENV
        echo "TF_VAR_aws_access_key_id=${{ secrets.TF_VAR_aws_access_key_id }}" >> $GITHUB_ENV
        echo "TF_VAR_aws_secret_access_key=${{ secrets.TF_VAR_aws_secret_access_key }}" >> $GITHUB_ENV

    - name: Run Terraform Commands
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
